"""
Layer 0 REST API: wraps the existing CLI pipeline (train.py/evaluate.py/
predict.py) behind HTTP endpoints, so a future frontend/scheduler can call
it instead of shelling out to scripts. No model/physics logic lives here -
every endpoint just calls the same functions the CLIs already use
(ges_uretim_tahmini.py is untouched).

Run locally:
    uvicorn api:app --reload

Interactive docs (auto-generated by FastAPI): http://127.0.0.1:8000/docs
"""

from datetime import date
from pathlib import Path

import joblib
import numpy as np
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from sklearn.metrics import mean_absolute_error, mean_squared_error

from evaluate import hit_rate, normalized_mae
from ges_uretim_tahmini import build_physical_baseline, calibrate_site_parameters, predict_production, train_residual_model
from plants import PlantNotFoundError, geometry_kwargs, list_plants, load_plant
from shared import ApiError
from train import load_training_data, split_train_test
from weather import fetch_weather_forecast, fetch_weather_forecast_ensemble

app = FastAPI(
    title="GES_predict API",
    description="Hybrid physical+ML solar production forecasting - HTTP layer over the existing CLI pipeline.",
    version="0.1.0",
)

MODELS_DIR = Path("models")


class PlantOut(BaseModel):
    plant_id: int
    name: str
    lat: float
    lon: float
    capacity_mw: float


class TrainResult(BaseModel):
    plant_id: int
    rows: int
    start: str
    end: str
    efficiency_scale: float
    temp_coeff: float
    ac_capacity_mw: float
    model_path: str


class EvaluateResult(BaseModel):
    plant_id: int
    test_days: int
    physical_mae_mwh: float
    physical_rmse_mwh: float
    physical_nmae_pct: float
    hybrid_mae_mwh: float
    hybrid_rmse_mwh: float
    hybrid_nmae_pct: float
    improvement_pct: float
    accuracy_pct: float
    hit_rate_physical_pct: float
    hit_rate_hybrid_pct: float


class PredictionPoint(BaseModel):
    timestamp: str
    predicted_mwh: float


def _get_plant_or_404(plant_id: int) -> dict:
    try:
        return load_plant(plant_id)
    except PlantNotFoundError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc


def _load_training_data_or_404(plant_id: int):
    try:
        return load_training_data(plant_id)
    except FileNotFoundError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc


@app.get("/health")
def health() -> dict:
    return {"status": "ok"}


@app.get("/plants", response_model=list[PlantOut])
def get_plants():
    registry = list_plants()
    return [
        PlantOut(plant_id=plant_id, name=p["name"], lat=p["lat"], lon=p["lon"], capacity_mw=p["capacity_mw"])
        for plant_id, p in registry.items()
    ]


@app.get("/plants/{plant_id}", response_model=PlantOut)
def get_plant(plant_id: int):
    plant = _get_plant_or_404(plant_id)
    return PlantOut(plant_id=plant_id, name=plant["name"], lat=plant["lat"], lon=plant["lon"],
                     capacity_mw=plant["capacity_mw"])


@app.post("/plants/{plant_id}/train", response_model=TrainResult)
def train_plant(plant_id: int):
    """Equivalent to `python train.py --plant-id <id> --output models/<id>/model.joblib`."""
    plant = _get_plant_or_404(plant_id)
    df = _load_training_data_or_404(plant_id)

    geometry = geometry_kwargs(plant)
    calibration = calibrate_site_parameters(df, plant["lat"], plant["lon"], plant["capacity_mw"], **geometry)
    baseline = build_physical_baseline(
        df, plant["lat"], plant["lon"], plant["capacity_mw"],
        temp_coeff=calibration["temp_coeff"], efficiency_scale=calibration["efficiency_scale"], **geometry,
    )
    model = train_residual_model(df, baseline, plant["lat"], plant["lon"])

    bundle = {"model": model, "calibration": calibration, "plant": plant}
    output_path = MODELS_DIR / str(plant_id) / "model.joblib"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(bundle, output_path)

    return TrainResult(
        plant_id=plant_id, rows=len(df),
        start=str(df["timestamp"].min()), end=str(df["timestamp"].max()),
        efficiency_scale=calibration["efficiency_scale"], temp_coeff=calibration["temp_coeff"],
        ac_capacity_mw=calibration["ac_capacity_mw"], model_path=str(output_path),
    )


@app.get("/plants/{plant_id}/evaluate", response_model=EvaluateResult)
def evaluate_plant(plant_id: int, test_days: int = 30, tolerance_pct: float = 3.0):
    """Equivalent to `python evaluate.py --plant-id <id> --test-days <test_days>`."""
    plant = _get_plant_or_404(plant_id)
    df = _load_training_data_or_404(plant_id)

    train_df, test_df = split_train_test(df, test_days=test_days)
    lat, lon, capacity_mw = plant["lat"], plant["lon"], plant["capacity_mw"]
    geometry = geometry_kwargs(plant)

    # Kalibrasyon sadece train_df'ten - test setine sızmasın.
    calibration = calibrate_site_parameters(train_df, lat, lon, capacity_mw, **geometry)
    temp_coeff, efficiency_scale = calibration["temp_coeff"], calibration["efficiency_scale"]
    ac_capacity_mw = calibration["ac_capacity_mw"]

    baseline_train = build_physical_baseline(train_df, lat, lon, capacity_mw, temp_coeff, efficiency_scale, **geometry)
    model = train_residual_model(train_df, baseline_train, lat, lon)

    baseline_test = build_physical_baseline(test_df, lat, lon, capacity_mw, temp_coeff, efficiency_scale, **geometry)
    hybrid_test = predict_production(
        test_df, lat, lon, capacity_mw, model,
        temp_coeff=temp_coeff, efficiency_scale=efficiency_scale, ac_capacity_mw=ac_capacity_mw, **geometry,
    )

    actual = test_df["production_mwh"]
    physical_mae = mean_absolute_error(actual, baseline_test)
    physical_rmse = float(np.sqrt(mean_squared_error(actual, baseline_test)))
    hybrid_mae = mean_absolute_error(actual, hybrid_test)
    hybrid_rmse = float(np.sqrt(mean_squared_error(actual, hybrid_test)))
    improvement = (1 - hybrid_mae / physical_mae) * 100 if physical_mae else 0.0
    physical_nmae = normalized_mae(actual, baseline_test, capacity_mw)
    hybrid_nmae = normalized_mae(actual, hybrid_test, capacity_mw)
    physical_hit = hit_rate(actual, baseline_test, capacity_mw, tolerance_pct)
    hybrid_hit = hit_rate(actual, hybrid_test, capacity_mw, tolerance_pct)

    return EvaluateResult(
        plant_id=plant_id, test_days=test_days,
        physical_mae_mwh=physical_mae, physical_rmse_mwh=physical_rmse, physical_nmae_pct=physical_nmae,
        hybrid_mae_mwh=hybrid_mae, hybrid_rmse_mwh=hybrid_rmse, hybrid_nmae_pct=hybrid_nmae,
        improvement_pct=improvement, accuracy_pct=100 - hybrid_nmae,
        hit_rate_physical_pct=physical_hit, hit_rate_hybrid_pct=hybrid_hit,
    )


@app.post("/plants/{plant_id}/predict", response_model=list[PredictionPoint])
def predict_plant(plant_id: int, start: date, end: date, ensemble: bool = False):
    """Equivalent to `python predict.py --plant-id <id> --start ... --end ...`.

    Requires a trained model (POST /plants/{plant_id}/train first) and
    network access to Open-Meteo's forecast API (~16 days ahead only).
    """
    if start > end:
        raise HTTPException(status_code=400, detail="start date must not be after end date")

    model_path = MODELS_DIR / str(plant_id) / "model.joblib"
    if not model_path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"No trained model at {model_path}. POST /plants/{plant_id}/train first.",
        )

    bundle = joblib.load(model_path)
    model, calibration, plant = bundle["model"], bundle["calibration"], bundle["plant"]
    lat, lon, capacity_mw = plant["lat"], plant["lon"], plant["capacity_mw"]

    fetch_fn = fetch_weather_forecast_ensemble if ensemble else fetch_weather_forecast
    try:
        weather_df = fetch_fn(lat, lon, start, end)
    except ApiError as exc:
        raise HTTPException(status_code=502, detail=str(exc)) from exc

    if weather_df.empty:
        raise HTTPException(
            status_code=422,
            detail="No forecast data returned - Open-Meteo's forecast API only covers "
                   "today through ~16 days ahead; the requested range may be out of that window.",
        )

    prediction = predict_production(
        weather_df, lat, lon, capacity_mw, model,
        temp_coeff=calibration["temp_coeff"], efficiency_scale=calibration["efficiency_scale"],
        ac_capacity_mw=calibration["ac_capacity_mw"], **geometry_kwargs(plant),
    )

    return [
        PredictionPoint(timestamp=ts.isoformat(), predicted_mwh=round(float(p), 2))
        for ts, p in zip(weather_df["timestamp"], prediction)
    ]
